export const MOCK_INVENTORY = [
  {
    id: '1',
    name: 'Carrots',
    emoji: '🥕',
    quantity: 6,
    status: 'today',
    statusText: 'Fresh for today',
    backgroundColor: '#FFB366',
    expirationDate: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Tomatoes',
    emoji: '🍅',
    quantity: 3,
    status: 'today',
    statusText: 'Fresh for today',
    backgroundColor: '#FF8A80',
    expirationDate: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Eggplant',
    emoji: '🍆',
    quantity: 4,
    status: 'tomorrow',
    statusText: 'Fresh until tomorrow',
    backgroundColor: '#CE93D8',
    expirationDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    name: 'Fruit salad',
    emoji: '🥭',
    quantity: 4,
    status: 'tomorrow',
    statusText: 'Fresh until tomorrow',
    backgroundColor: '#81C784',
    expirationDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    name: 'Pineapple',
    emoji: '🍍',
    quantity: 1,
    status: 'tomorrow',
    statusText: 'Fresh until tomorrow',
    backgroundColor: '#FFD54F',
    expirationDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    name: 'Watermelon',
    emoji: '🍉',
    quantity: 1,
    status: 'fresh',
    statusText: 'Fresh until tomorrow',
    backgroundColor: '#A5D6A7',
    expirationDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    name: 'Bread',
    emoji: '🍞',
    quantity: 4,
    status: 'expired',
    statusText: 'Past due date',
    backgroundColor: '#FFAB91',
    expirationDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];