import { StyleSheet } from 'react-native';

export const addStyles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  cancelButton: {
    color: '#636e72',
    fontSize: 16,
  },
  modalTitle: {
    color: '#2d3436',
    fontSize: 18,
    fontWeight: 'bold',
  },
  saveButton: {
    color: '#74b9ff',
    fontSize: 16,
    fontWeight: '600',
  },
  modalContent: {
    flex: 1,
    paddingHorizontal: 20,
  },
  inputSection: {
    marginVertical: 20,
  },
  label: {
    color: '#2d3436',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
  },
  textInput: {
    backgroundColor: 'white',
    color: '#2d3436',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    fontSize: 16,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  categoryCard: {
    width: '30%',
    aspectRatio: 1,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    opacity: 0.8,
  },
  selectedCategory: {
    opacity: 1,
    borderWidth: 3,
    borderColor: 'white',
  },
  categoryEmoji: {
    fontSize: 24,
    marginBottom: 4,
  },
  categoryName: {
    color: '#2d3436',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButton: {
    backgroundColor: '#74b9ff',
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonText: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
  },
  quantityInput: {
    backgroundColor: '#f5f5f5',
    color: '#2d3436',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    fontSize: 18,
    fontWeight: 'bold',
    marginHorizontal: 20,
    minWidth: 80,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  unitPickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  unitNavButton: {
    backgroundColor: '#74b9ff',
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unitNavButtonText: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
  unitDisplay: {
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    marginHorizontal: 20,
    width: 150,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  unitDisplayScroll: {
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    marginHorizontal: 20,
    width: 150,
    height: 50,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  unitScrollItem: {
    width: 150,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  unitDisplayText: {
    color: '#2d3436',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  pickerContainer: {
    position: 'relative',
    width: 280,
    height: 120,
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  pickerScroll: {
    flex: 1,
  },
  pickerScrollContent: {
    paddingVertical: 40,
  },
  pickerItem: {
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickerItemText: {
    color: '#b2bec3',
    fontSize: 16,
    fontWeight: '500',
  },
  pickerItemTextSelected: {
    color: '#2d3436',
    fontSize: 18,
    fontWeight: 'bold',
  },
  pickerHighlight: {
    position: 'absolute',
    top: 40,
    left: 0,
    right: 0,
    height: 40,
    backgroundColor: 'rgba(116, 185, 255, 0.15)',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#74b9ff',
  },
  unitChip: {
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  unitChipSelected: {
    backgroundColor: '#74b9ff',
    borderColor: '#74b9ff',
  },
  unitChipText: {
    color: '#636e72',
    fontSize: 13,
    fontWeight: '500',
  },
  unitChipTextSelected: {
    color: 'white',
    fontWeight: '600',
  },
  daysContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  daysButton: {
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    flex: 1,
    marginHorizontal: 4,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  selectedDays: {
    backgroundColor: '#74b9ff',
    borderColor: '#74b9ff',
  },
  daysText: {
    color: '#636e72',
    fontSize: 14,
    fontWeight: '500',
  },
  selectedDaysText: {
    color: 'white',
  },
  datePickerButton: {
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  datePickerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateInfo: {
    flex: 1,
    marginLeft: 12,
  },
  dateText: {
    color: '#2d3436',
    fontSize: 16,
    fontWeight: '600',
  },
  dateSubtext: {
    color: '#74b9ff',
    fontSize: 14,
    marginTop: 2,
  },
  quickDatesContainer: {
    marginTop: 8,
  },
  quickDatesLabel: {
    color: '#999',
    fontSize: 14,
    marginBottom: 8,
  },
  quickDatesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  quickDateButton: {
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    flex: 1,
    marginHorizontal: 2,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  quickDateText: {
    color: '#636e72',
    fontSize: 12,
    fontWeight: '500',
  },
  datePickerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  datePickerModal: {
    backgroundColor: '#f5f5f5',
    borderRadius: 20,
    width: '100%',
    maxWidth: 400,
    paddingBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  datePickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  datePickerTitle: {
    color: '#333',
    fontSize: 18,
    fontWeight: 'bold',
  },
  datePickerDone: {
    color: '#74b9ff',
    fontSize: 17,
    fontWeight: '600',
  },
  calendarContainer: {
    padding: 20,
  },
  calendarNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  navButton: {
    padding: 8,
  },
  monthYearText: {
    color: '#333',
    fontSize: 18,
    fontWeight: 'bold',
  },
  weekDaysRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  weekDayText: {
    flex: 1,
    textAlign: 'center',
    color: '#666',
    fontSize: 14,
    fontWeight: '600',
  },
  daysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  emptyDay: {
    width: `${100/7}%`,
    aspectRatio: 1,
  },
  dayCell: {
    width: `${100/7}%`,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  todayCell: {
    backgroundColor: '#e8f5e9',
    borderRadius: 8,
  },
  selectedCell: {
    backgroundColor: '#74b9ff',
    borderRadius: 8,
  },
  dayText: {
    color: '#333',
    fontSize: 16,
    fontWeight: '500',
  },
  todayText: {
    color: '#74b9ff',
    fontWeight: 'bold',
  },
  selectedText: {
    color: 'white',
    fontWeight: 'bold',
  },
  categoryPickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryPickerItem: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryPickerItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  categoryPickerItemEmoji: {
    fontSize: 24,
    marginRight: 12,
  },
  categoryPickerItemText: {
    color: '#666',
    fontSize: 16,
    fontWeight: '500',
  },
  categoryPickerItemEmoji: {
    fontSize: 24,
    marginRight: 12,
  },
  categoryPickerItemText: {
    color: '#b2bec3',
    fontSize: 16,
    fontWeight: '500',
  },
  categoryPickerItemSelected: {
    color: '#2d3436',
    fontSize: 17,
    fontWeight: 'bold',
  },
  categoryPickerColorIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 8,
  },
});

export const calendarStyles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  closeButton: {
    color: '#636e72',
    fontSize: 16,
  },
  title: {
    color: '#2d3436',
    fontSize: 18,
    fontWeight: 'bold',
  },
  placeholder: {
    width: 60,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  navButton: {
    padding: 8,
  },
  monthYear: {
    color: '#2d3436',
    fontSize: 20,
    fontWeight: 'bold',
  },
  weekDays: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  weekDay: {
    flex: 1,
    textAlign: 'center',
    color: '#636e72',
    fontSize: 14,
    fontWeight: '600',
  },
  calendar: {
    flex: 1,
    paddingHorizontal: 20,
  },
  daysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingTop: 10,
  },
  dayContainer: {
    width: `${100/7}%`,
    aspectRatio: 1,
    padding: 2,
    marginBottom: 4,
  },
  todayContainer: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
  },
  emptyDay: {
    width: `${100/7}%`,
    aspectRatio: 1,
  },
  dayNumber: {
    color: '#2d3436',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 4,
  },
  todayText: {
    color: '#74b9ff',
    fontWeight: 'bold',
  },
  itemsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 2,
  },
  itemDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemEmoji: {
    fontSize: 10,
  },
  moreIndicator: {
    backgroundColor: '#666',
    borderRadius: 6,
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginLeft: 2,
  },
  moreText: {
    color: 'white',
    fontSize: 8,
    fontWeight: 'bold',
  },
  countBadge: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    backgroundColor: '#ff5252',
    borderRadius: 6,
    width: 12,
    height: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  countBadgeText: {
    color: 'white',
    fontSize: 7,
    fontWeight: 'bold',
  },
});

export const dateDetailStyles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  closeButton: {
    color: '#74b9ff',
    fontSize: 16,
    fontWeight: '600',
  },
  title: {
    color: '#2d3436',
    fontSize: 18,
    fontWeight: 'bold',
  },
  placeholder: {
    width: 60,
  },
  dateHeader: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  dateText: {
    color: '#2d3436',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  itemCount: {
    color: '#636e72',
    fontSize: 14,
  },
  itemsList: {
    flex: 1,
    paddingHorizontal: 20,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
  },
  emptyEmoji: {
    fontSize: 60,
    marginBottom: 16,
  },
  emptyTitle: {
    color: '#2d3436',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  emptySubtitle: {
    color: '#636e72',
    fontSize: 14,
    textAlign: 'center',
  },
  itemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    padding: 16,
    marginVertical: 6,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  itemIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  itemEmoji: {
    fontSize: 24,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    color: '#2d3436',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  itemQuantity: {
    color: '#636e72',
    fontSize: 14,
    marginBottom: 2,
  },
  itemStatus: {
    color: '#636e72',
    fontSize: 12,
  },
  statusIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 12,
  },
});